# Generated by Django 4.2.2 on 2023-06-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha_registro',
            field=models.DateField(),
        ),
    ]
